# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: .github
repository:
  homepage: https://git.sr.ht/~tsdh/swayr
# you can extend settings using https://probot.github.io/apps/settings/
